### ISSUE TITLE
请教个代码问题

### ISSUE THREAD

**Issue by yue5667** [kidozh/keras_detect_tool_wear#3]
![image](https://user-images.githubusercontent.com/58220187/71323046-f2672200-2509-11ea-8003-3cd5bca942ae.png)
![image](https://user-images.githubusercontent.com/58220187/71323050-f98e3000-2509-11ea-8240-806c6194283d.png)
不知道什么原因，请教你一下，还望解答，谢谢啦

**Comment by kidozh** [comment]
可能是最大磨损量和各齿磨损量当时代码有些混淆。
你可以将model.py中最后一个Dense层的dim从3改为1，应该就能完成对于三齿磨损量的预测。

**Comment by yue5667** [comment]
你说的是这个地方吗，可是这个地方好像本来设置的就是1

**Comment by kidozh** [comment]
不好意思 说反了 ，这里你把1改成3吧，这样预测的就是各齿磨损量了。

**Comment by yue5667** [comment]
昂，是这个意思，懂了懂了，感谢你抽时间回复，谢谢啦发自我的iPhone------------------ 原始邮件 ------------------发件人: Kido Zhang  <notifications@github.com>发送时间: 2019年12月22日 22:55收件人: kidozh/keras_detect_tool_wear <keras_detect_tool_wear@noreply.github.com>抄送: yue5667 <yzf5667@163.com>, Author <author@noreply.github.com>主题: 回复：[kidozh/keras_detect_tool_wear] 请教个代码问题 (#3)不好意思 说反了 ，这里你把1改成3吧，这样预测的就是各齿磨损量了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kidozh/keras_detect_tool_wear/issues/3?email_source=notifications\u0026email_token=AN4F5G6N2JJTJXIDVQ7VLO3QZ55VHA5CNFSM4J6MAMU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPR2TQ#issuecomment-568270158",
"url": "https://github.com/kidozh/keras_detect_tool_wear/issues/3?email_source=notifications\u0026email_token=AN4F5G6N2JJTJXIDVQ7VLO3QZ55VHA5CNFSM4J6MAMU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPR2TQ#issuecomment-568270158",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
